# springboot-service-clusterip.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-clusterip
  namespace: dev-namespace
  labels:
    app: springboot-hello
spec:
  type: ClusterIP
  selector:
    app: springboot-hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http