apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-nodeport
  namespace: dev-namespace
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30333
      