apiVersion: v1
kind: Pod
metadata:
  name: my-custom-namespace-pod
  namespace: dev-namespace
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80